version: '2'
services:
  postgres:
    image: postgres:9.6.2
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=form3
    volumes:
      - ./data/postgres:/var/lib/postgresql/data