spring:
  application:
    name: @project.name@
  datasource:
    url: jdbc:postgresql://localhost:5432/form3?currentSchema=form3
    username: postgres
    password: passw0rd
    driverClassName: org.postgresql.Driver
    continue-on-error: true
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
      data-source-properties:
        socketTimeout: 120
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show_sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    open-in-view: false
  jackson:
    default-property-inclusion: non_absent
    serialization:
      write_dates_as_timestamps: false
    deserialization:
      adjust_dates_to_context_time_zone: false
      fail_on_unknown_properties: false
  hateoas:
    use-hal-as-default-json-media-type: false

flyway:
  enabled: true
  locations: classpath:/db/migration, classpath:/db/data

endpoints:
  mappings:
    sensitive: false
    enabled: true

info:
  app:
    name: ${spring.application.name}
    description: @project.description@
    version: @project.version@

server:
  port: 8080